nodeLinker: node-modules

# Cấu hình bỏ qua lỗi peer dependency đúng cách cho Yarn 4
packageExtensions:
  "@schedule-x/vue@*":
    peerDependencies:
      "@schedule-x/date-picker": "*"
  "@schedule-x/calendar@*":
    peerDependencies:
      "temporal-polyfill": "*"

# Cho phép cập nhật nếu có sai lệch nhẹ về checksum
checksumBehavior: update