nodeLinker: node-modules

# Hạ mức độ nghiêm trọng của lỗi Peer Dependency
peerDependencyCheck:
  severity: warning

# Giữ lại các extension này để hỗ trợ resolution
packageExtensions:
  "@schedule-x/vue@*":
    peerDependencies:
      "@schedule-x/date-picker": "*"
  "@schedule-x/calendar@*":
    peerDependencies:
      "temporal-polyfill": "*"

checksumBehavior: update