nodeLinker: node-modules

# Cho phép bỏ qua các lỗi không khớp phiên bản peer dependency
peerDependencyCheck:
  severity: warning

# Cho phép thay đổi checksum nếu môi trường khác biệt
checksumBehavior: update